"""add profile PHOTO

Revision ID: c3dc20786298
Revises: 976b9878d0b3
Create Date: 2024-09-30 20:30:11.024276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3dc20786298'
down_revision = '976b9878d0b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_photo_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_photo_path')
    # ### end Alembic commands ###
